papers/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('paper', views.paper, name = 'paper'),
    path('read', views.read, name = 'read'),
    path('readlist', views.readlist, name = 'readlist'),
    path('projects', views.projects, name = 'projects'),
    path('project/<int:project_id>', views.project, name = 'project'),
    path('readproject/<int:project_id>', views.read_project, name = 'readproject'),
    path('projectstatus', views.project_status, name = 'status'),
    path('delete', views.delete_project, name = 'delete'),
]

spiresearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('papers/', include('papers.urls')),
    path('', RedirectView.as_view(url='papers/', permanent=True)),

]

papers/models.py
from django.db import models
from accounts.models import CustomUser
# Create your models here.

class UserRead(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    urls = models.TextField()

    def add_url(self, url):
        if url not in self.urls.split(',')[:-1]:
            self.urls += url + ','

    def remove_url(self,url):
        self.urls = self.urls.replace(url + ',','')

    def all_urls(self):
        return self.urls.split(',')[:-1]

class UserProject(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length = 250, blank=True, default='')
    description = models.TextField(max_length = 1250, blank=True, default='')
    urls = models.TextField()

    def rename_project(self, name):
        self.name = name

    def add_url(self, url):
        if url not in self.urls.split(',')[:-1]:
            self.urls += url + ','

    def remove_url(self,url):
        self.urls = self.urls.replace(url + ',','')

    def all_urls(self):
        return self.urls.split(',')[:-1]

papers/forms.py
from django import forms
from .validators import validate_url
from .models import UserProject

class URLForm(forms.Form):
    paper_url = forms.URLField(
        widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder': 'e.g. https://inspirehep.net/literature/1480357'
        }),
        validators=[validate_url]
    )

class NewProjectForm(forms.ModelForm):
    class Meta:
        model = UserProject
        fields = ["name", "description"]
        labels = {
            "name": "Project Name",
            "description": "Description",
        }

papers/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import json
from urllib.parse import unquote

from .models import CustomUser, UserRead, UserProject
from .forms import URLForm, NewProjectForm

def index(request):
    form = URLForm
    return render(request, 'papers/index.html', {'form': form})

def paper(request):
    if request.method == 'POST':
        form = URLForm(request.POST)
        ref_form = URLForm
        if form.is_valid():
            paper_url = form.cleaned_data['paper_url']
            readlist = False
            projects = False
            if request.user.is_authenticated:
                readlist = UserRead.objects.filter(user = request.user).first()
                if readlist:
                    readlist = ','.join(readlist.all_urls())
                else:
                    readlist = ''
                projects = UserProject.objects.filter(user = request.user)
            return render(request, 'papers/paper.html', {
            'paper_url': paper_url,
            'form': ref_form,
            'readlist': readlist,
            'projects': projects,
            })
        if form.errors['paper_url']:
            messages.error(request, form.errors['paper_url'])
        else:
            messages.error(request, 'Sorry, something went wrong')
        return redirect('index')
    else:
        return redirect('index')


@login_required
def readlist(request):
    ref_form = URLForm
    readlist = UserRead.objects.filter(user = request.user).first()
    projects = UserProject.objects.filter(user = request.user)
    if readlist and readlist != "":
        return render(request, 'papers/readlist.html', {
        'readlist': ','.join(readlist.all_urls()),
        'form': ref_form,
        'projects': projects,
        })
    else:
        return render(request, 'papers/readlist.html')

@login_required
@csrf_exempt
def read(request):
    if request.method != "PUT":
        return JsonResponse({"error": "PUT request required"}, status = 400)
    user_read = UserRead.objects.filter(user = request.user).first()
    json_data = json.loads(request.body)
    read_url = json_data.get("read_url", "")
    if user_read:
        if read_url in user_read.all_urls():
            user_read.remove_url(read_url)
            user_read.save()
            return JsonResponse({"message": "Readlist Subtraction"}, status = 200)
        else:
            user_read.add_url(read_url)
            user_read.save()
            return JsonResponse({"message": "Readlist Addition"}, status = 200)
    else:
        UserRead.objects.create(user = request.user, urls = read_url + ',')
        return JsonResponse({"message": "Readlist Created"}, status = 200)


@login_required
def projects(request):
    if request.method == "POST":
        submitted_form = NewProjectForm(request.POST)
        if submitted_form.is_valid():
            name = submitted_form.cleaned_data['name']
            description = submitted_form.cleaned_data['description']
            UserProject.objects.create(
                user = request.user,
                name = name,
                description = description)
        else:
            messages.error(request, "Sorry, something went wrong.")
        create_form = NewProjectForm
        projects = UserProject.objects.filter(user = request.user)
        return render(request, 'papers/projects.html',{
            'form': create_form,
            'projects': projects,
        })
    else:
        form = NewProjectForm
        projects = UserProject.objects.filter(user = request.user)
        return render(request, 'papers/projects.html',{
            'form': form,
            'projects': projects,
        })

@login_required
def project(request, project_id):
    ref_form = URLForm
    project = UserProject.objects.get(id = project_id)
    if project.user != request.user:
        messages.error(request, "Only acess your own projects.")
        return redirect('projects')
    readlist = UserRead.objects.filter(user = request.user).first()
    if readlist:
        readlist = ','.join(readlist.all_urls())
    else:
        readlist = ''
    return render(request, 'papers/project.html', {
        'project': project,
        'readlist': readlist,
        'projectlist': ','.join(project.all_urls()),
        'form': ref_form
    })

@login_required
@csrf_exempt
def read_project(request, project_id):
    if request.method != "PUT":
        return JsonResponse({"error": "PUT request required"}, status = 400)
    project = UserProject.objects.get(id = project_id)
    if project.user != request.user:
        messages.error(request, "Only acess your own projects.")
        return redirect('projects')
    json_data = json.loads(request.body)
    read_url = json_data.get("read_url", "")
    if read_url in project.all_urls():
        project.remove_url(read_url)
        project.save()
        return JsonResponse({"message": "Project Subtraction"}, status = 200)
    else:
        project.add_url(read_url)
        project.save()
        return JsonResponse({"message": "Project Addition"}, status = 200)

@login_required
@csrf_exempt
def project_status(request):
    if request.method != 'POST':
        return redirect('index')
    json_data = json.loads(request.body)
    url = json_data['url']
    project_id = json_data['projectId']
    project = UserProject.objects.get(id = project_id)
    if project.user != request.user:
        messages.error(request, "Only acess your own projects.")
        return redirect('projects')
    status = 'True' if url in project.all_urls() else 'False'
    return JsonResponse({"status" : status}, status = 200)

@login_required
def delete_project(request):
    if request.method != 'POST':
        return redirect('projects')
    project = UserProject.objects.get(id = request.POST['del'])
    if project.user != request.user:
        messages.error(request, "Only acess your own projects.")
        return redirect('projects')
    project.delete()
    messages.success(request, "Project Deleted")
    return redirect('projects')

papers/templates/papers/index.html
{% extends "layout.html" %}

{% block body %}
{% load static %}
<div class="p-0" id='messages'>
    {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    {% endif %}
</div>

<div class='container-fluid'>
    <h1 class='center'>Inspire Searcher</h1>
    <form id="paperForm" action="{% url 'paper' %}" method="post">
        {% csrf_token %}
        <div class='input-group input-group-lg'>
            <span class="input-group-text bg-light" id="url_label">URL</span>
            {{ form.paper_url }}
            <input type="submit" value="Submit" class="btn btn-primary">
        </div>
    </form>
</div>

<div class="card container-fluid">
    <h3>Welcome to Inspire Searcher</h3>
    <div>
        This is a tool to help locate relevant research papers on INSPIRE-HEP using
        the references of a paper. Search for a paper through its link on INSPIRE, then
        you can sort and search its references to find potentially useful papers. Create
        an account for additional options.
    </div>
    <div>
        <h4>Current Options</h4>
        <ul>
            <li>Sort and search references for a paper.</li>
            <li>Bookmark papers in a readlist.</li>
            <li>Bookmark papers for specific projects.</li>
        </ul>

        <h4>Future Plans</h4>
        <ul>
            <li>Automatic citation generation.</li>
            <li>Extension to other databases.</li>
        </ul>
    </div>
</div>

{% endblock %}

papers/templates/papers/paper.html
{% extends "layout.html" %}

{% block body %}
{% load static %}
<div class="p-0" id='messages'>
    {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    {% endif %}
</div>
<script src="{% static 'papers/common.js' %}"></script>
<script src="{% static 'papers/inspire.js' %}"></script>
<script src="{% static 'papers/paper.js' %}"></script>

<form action="{% url 'paper' %}" method="post" id="refForm" target="_blank" hidden novalidate>
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" id="refSubmit">
</form>

{% if paper_url %}
<div id="paperUrl" hidden>{{paper_url}}</div>
{% endif %}

{% if user.is_authenticated %}
<div id="readlist" hidden>{{readlist}}</div>
{% endif %}

<div class="card container-fluid" id="paperData">
    <h2 id="title"></h2>
    <div id="authors"></div>
    <div id="abstract"></div>
    <div id="citations"></div>
    <div id="pub"></div>
    <div id="links"></div>

    {% if user.is_authenticated %}
        <div class='row'>
            <div class="col-auto">
                <button type="button" id="read" class="btn btn-primary">Add to Readlist</button>
            </div>
            <div class="col-auto">
                <div class="input-group p-0" id="projects">
                    <select class="form-select" id="projectSelect">
                      <option value="0" selected>Choose...</option>
                      {% for project in projects %}
                        <option value="{{project.id}}">{{project.name}}</option>
                      {% endfor %}
                    </select>
                    <button class="btn btn-primary" type="button" id="projectSelectBtn" disabled>Select</button>
                </div>
            </div>
        </div>
    {% endif %}
</div>
<br>
<div class="card container-fluid">
    <h3>References</h3>

    <h4>INSPIRE Records</h4>
        <div class="input-group">
            <span class="input-group-text bg-light">Search</span>
            <input class='form-control' type="text" name="inspireSearch" id='inspireSearch'>
            <small class="w-100 text-muted">Note. Only displayed authors are searched currently.</small>
            <div class="form-check">
                <label class='form-check-label' for="hasArxiv">arXiv available</label>
                <input class='form-check-input' type="checkbox" name="hasArxiv" id='hasArxiv'>
            </div>
        </div>

        <div id="inspireRecords" class="table-responsive"></div>

    <h4>Other Records</h4>

        <div class="input-group">
            <span class="input-group-text bg-light">Search</span>
            <input class='form-control' type="text" name="miscSearch" id='miscSearch'>
            <small class="w-100 text-muted">Note. Only displayed authors are searched currently.</small>
        </div>

        <div id="miscRecords" class="table-responsive"></div>
</div>




{% endblock %}

papers/templates/papers/project.html
{% extends "layout.html" %}

{% block body %}
{% load static %}
<div class="p-0" id='messages'>
    {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    {% endif %}
</div>
<script src="{% static 'papers/common.js' %}"></script>
<script src="{% static 'papers/inspire.js' %}"></script>
<script src="{% static 'papers/project.js' %}"></script>

<form action="{% url 'paper' %}" method="post" id="refForm" target="_blank" hidden novalidate>
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" id="refSubmit">
</form>

<div id="readlist" hidden>{{readlist}}</div>

<div id='projectId' hidden>{{project.id}}</div>
<div class="card container-fluid">
    <a href="{% url 'projects' %}"> &lt; Back to Projects</a>
    <h3>{{project.name}}</h3>
    <form  action="{% url 'delete' %}" method="post">
        {% csrf_token %}
        <input type="text" name="del" value="{{project.id}}" hidden>
        <input type="submit" value="Delete" class="btn btn-primary">
    </form>
    {{project.description}}
    <div>
    <h4>Saved Records</h4>

        <div class="input-group">
            <span class="input-group-text bg-light">Search</span>
            <input class='form-control' type="text" name="inspireSearch" id='inspireSearch'>
            <small class="w-100 text-muted">Note. Only displayed authors are searched currently.</small>
            <div class="form-check">
                <label class='form-check-label' for="hasArxiv">arXiv available</label>
                <input class='form-check-input' type="checkbox" name="hasArxiv" id='hasArxiv'>
            </div>
        </div>

        <div id="inspireRecords" class="table-responsive"></div>

        {% if projectlist %}
            <div id="projectlist" hidden>{{projectlist}}</div>
        {% endif %}
    <div>
</div>



{% endblock %}

papers/templates/papers/projects.html
{% extends "layout.html" %}

{% block body %}
{% load static %}
{% load add_class %}
<div class="p-0" id='messages'>
    {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    {% endif %}
</div>
<script src="{% static 'papers/common.js' %}"></script>
<script src="{% static 'papers/inspire.js' %}"></script>
<script src="{% static 'papers/projects.js' %}"></script>

{% if messages %}
<ul id="errors" style="list-style: circle;">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<div class="card container-fluid">
    <h3>Projects</h3>
    <div>
        <button type="button" id="createProject" class="btn btn-primary">Create Project</button>

        <form action="{% url 'projects' %}" method="post" style="display:none;" id="createProjectForm">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_name" class="form-label">{{form.name.label}}</label>
                {{form.name | add_class:"form-control" }}
                <label for="id_description" class="form-label">{{form.description.label}}</label>
                {{form.description | add_class:"form-control" }}
                <div>
                    <button type="submit" class="btn btn-primary mb-3">Submit</button>
                </div>
            </div>
        </form>
    </div>


    <ul class="list-group list-group-flush">
        {% for project in projects %}
        <li class="list-group-item">
            <a href='{% url "project" project.id %}'>{{project.name}}</a>
            <form  action="{% url 'delete' %}" method="post">
                {% csrf_token %}
                <input type="text" name="del" value="{{project.id}}" hidden>
                <input type="submit" value="Delete" class="btn btn-primary">
            </form>
        </li>
        {% endfor %}
    </ul>

</div>

{% endblock %}

papers/templates/papers/readlist.html
{% extends "layout.html" %}

{% block body %}
{% load static %}
<div class="p-0" id='messages'>
    {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    {% endif %}
</div>
<script src="{% static 'papers/common.js' %}"></script>
<script src="{% static 'papers/inspire.js' %}"></script>
<script src="{% static 'papers/readlist.js' %}"></script>

<form action="{% url 'paper' %}" method="post" id="refForm" target="_blank" hidden novalidate>
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" id="refSubmit">
</form>

{% if readlist %}
    <div id="readlist" hidden>{{readlist}}</div>
{% endif %}

<div class="input-group p-0" id="projects" hidden>
    <select class="form-select" id="projectSelect">
      <option value="0" selected>Choose...</option>
      {% for project in projects %}
        <option value="{{project.id}}">{{project.name}}</option>
      {% endfor %}
    </select>
    <button class="btn btn-primary" type="button" id="projectSelectBtn" disabled>Select</button>
</div>

<div class="card container-fluid">
    <h3>Readlist</h3>
    <h4>Saved Records</h4>

        <div class="input-group">
            <span class="input-group-text bg-light">Search</span>
            <input class='form-control' type="text" name="inspireSearch" id='inspireSearch'>
            <small class="w-100 text-muted">Note. Only displayed authors are searched currently.</small>
            <div class="form-check">
                <label class='form-check-label' for="hasArxiv">arXiv available</label>
                <input class='form-check-input' type="checkbox" name="hasArxiv" id='hasArxiv'>
            </div>
        </div>

        <div id="inspireRecords" class="table-responsive"></div>

</div>



{% endblock %}